### ISSUE TITLE
Spark 3.x

### ISSUE THREAD

**Issue by loicdescotte** [Gradiant/dockerized-spark#3]
Hi,

Thanks for this cool docker images.  Do you plan to build images for Spark 3.x ?

**Comment by cgiraldo** [comment]
Hi,

We have no plans to support Spark 3.x.
We made this image two years ago because we didn't find any good alternative.
Now, for Spark 3.x I recommend you to try bitnami image: 

[https://hub.docker.com/r/bitnami/spark](https://hub.docker.com/r/bitnami/spark)

I hope that helps,
